"""empty message

Revision ID: 0462a16ff813
Revises: 173d6326429f
Create Date: 2023-10-22 12:25:27.896895

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0462a16ff813'
down_revision = '173d6326429f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_ext', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_id_ext'), 'questions', ['id_ext'], unique=True)
    op.create_index(op.f('ix_questions_timestamp'), 'questions', ['timestamp'], unique=False)
    op.drop_index('ix_qustions_id_ext', table_name='qustions')
    op.drop_index('ix_qustions_timestamp', table_name='qustions')
    op.drop_table('qustions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qustions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('question_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('answer', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id_ext', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='qustions_pkey')
    )
    op.create_index('ix_qustions_timestamp', 'qustions', ['timestamp'], unique=False)
    op.create_index('ix_qustions_id_ext', 'qustions', ['id_ext'], unique=False)
    op.drop_index(op.f('ix_questions_timestamp'), table_name='questions')
    op.drop_index(op.f('ix_questions_id_ext'), table_name='questions')
    op.drop_table('questions')
    # ### end Alembic commands ###
