"""empty message

Revision ID: 173d6326429f
Revises: eee55ed2e4e0
Create Date: 2023-10-22 12:10:13.958540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '173d6326429f'
down_revision = 'eee55ed2e4e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qustions', sa.Column('id_ext', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_qustions_id_ext'), 'qustions', ['id_ext'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qustions_id_ext'), table_name='qustions')
    op.drop_column('qustions', 'id_ext')
    # ### end Alembic commands ###
